# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-11 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfid',
            name='out_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rfid',
            name='out_firm',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='rfid',
            name='rf_id_state',
            field=models.CharField(default='납품', max_length=4),
        ),
        migrations.AlterUniqueTogether(
            name='rfiddet',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='rfiddet',
            name='out_firm',
        ),
        migrations.RemoveField(
            model_name='rfiddet',
            name='rf_id_state',
        ),
    ]
