# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-11 05:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20171211_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rfid',
            old_name='in_date',
            new_name='mfr_date',
        ),
    ]
