# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-11 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20171211_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfid',
            name='out_firm',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rfid',
            name='rf_id_state',
            field=models.CharField(default='MFR', max_length=4),
        ),
    ]
