# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-11 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_auto_20171211_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfid',
            name='in_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
