# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-11 10:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_rfid_in_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('item_name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='out',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_date', models.DateField(default=datetime.date.today)),
                ('out_firm', models.CharField(blank=True, max_length=50)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Item')),
            ],
        ),
        migrations.AlterField(
            model_name='rfiddet',
            name='message',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
