# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-11 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_auto_20171211_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfid',
            name='rf_id_state',
            field=models.CharField(choices=[('MFR', '제품입고'), ('OUT', '납품'), ('IN', '수리입고'), ('WST', '폐기')], default='MFR', max_length=4),
        ),
    ]
