# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-11 10:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_auto_20171211_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='In',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_date', models.DateField(default=datetime.date.today)),
                ('out_firm', models.CharField(blank=True, max_length=50)),
                ('out_qty', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='out',
            name='out_qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(blank=True, help_text='Item Name', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rfid',
            name='mfr_date',
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='rfid',
            name='rf_id_state',
            field=models.CharField(choices=[('MFR', '제품입고'), ('OUT', '납품'), ('IN', '수리입고'), ('WST', '폐기')], default='MFR', max_length=3),
        ),
        migrations.AddField(
            model_name='in',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Item'),
        ),
    ]
