# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-11 11:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_auto_20171211_1958'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='In',
            new_name='ItemIn',
        ),
        migrations.RenameModel(
            old_name='out',
            new_name='ItemOut',
        ),
    ]
