# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-11 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_auto_20171211_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_qty', models.PositiveIntegerField(default=0)),
                ('out_qty', models.PositiveIntegerField(default=0)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Item')),
            ],
        ),
        migrations.RenameField(
            model_name='itemin',
            old_name='out_date',
            new_name='in_date',
        ),
        migrations.RenameField(
            model_name='itemin',
            old_name='out_firm',
            new_name='in_firm',
        ),
        migrations.RenameField(
            model_name='itemin',
            old_name='out_qty',
            new_name='in_qty',
        ),
    ]
